autoscaling:
  enabled: false

env:
  - name: TEST
    value: vault:dev-int/data/common03-kafka-credentials#authority3_usersroles

appConfig:
  spring: 
    data:
      redis:
        port: "6379"
        username: "default"
        password: ""
  simpl:
    ephemeral-proof:
      expire-after: 3m
