SERVICE_PORT: 8084
CONTAINER_PORT: 8084
DEPLOYMENT_IMAGE_PULL_POLICY: Always



deployment:
  label: poc

serviceAccount:
  enabled: true
  name: "adapter-sa"

podSecurityContext: 
  allowPrivilegeEscalation: false
