values:
  repo_URL: https://code.europa.eu/simpl/simpl-open/development/agents/governance-authority.git
  branch: v2.4.1

project: ${PROJECT}
domainSuffix: ${DOMAINSUFFIX}
namespaceTag:
  authority: ${AUTHNAMESPACETAG}
  common: ${COMMONSPACETAG}

resourcePreset: default
# resourcePreset: low

argocd:
  appname: ${NAMESPACE}
  namespace: ${ARGOCDNAMESPACE}

cluster:
  address: https://kubernetes.default.svc
  namespace: ${NAMESPACE}
  commonToolsNamespace: ${COMMONNAMESPACE}
  issuer: ${CLUSTERISSUER}

secrets:
  role:  ${SECRETROLE}
  secretEngine: ${SECRETENGINE}

keycloak:
  repo_URL: 'https://charts.bitnami.com/bitnami'
  chart_name: keycloak
  targetRevision: 22.2.5
  nameOverride: keycloak
  resourcesPreset: "none"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  valueFiles:
    - values.yaml

ejbca:
  repo_URL: 'https://keyfactor.github.io/ejbca-community-helm'
  targetRevision: 1.0.7
  chart_name: ejbca-community-helm
  fullnameOverride: ejbca-community-helm
  resources:
    requests:
      cpu: "500m"
      memory: "1024Mi"
    limits:
      cpu: "500m"
      memory: "1024Mi" 
  valueFiles:
    - values.yaml

tier1_gateway:
  projectID: "772"
  targetRevision: 2.5.0
  chart_name: tier1-gateway
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: "400m"
      memory: "512Mi"  
  valueFiles:
    - values.yaml

simpl_fe:
  projectID: "769"
  targetRevision: 2.5.0
  chart_name: simpl-fe
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: "400m"
      memory: "512Mi" 
  valueFiles:
    - values.yaml
    - values-authority.yaml

sap:
  projectID: "861"
  targetRevision: 2.5.1
  chart_name: security-attributes-provider
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: "400m"
      memory: "512Mi" 
  valueFiles:
    - values.yaml

users_roles:
  projectID: "771"
  targetRevision: 2.5.1
  chart_name: users-roles
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: "400m"
      memory: "512Mi" 
  valueFiles:
    - values.yaml


xsfc_catalogue:
  enabled: true
  projectID: "820"
  targetRevision: 1.0.11
  chart_name: fc-service
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi" 
  valueFiles:
    - values.yaml

onboarding:
  projectID: "770"
  targetRevision: 2.5.0
  chart_name: onboarding
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi" 

adapter:
  enabled: true
  projectID: "759"
  targetRevision: 1.0.13
  chart_name: poc-charts
  fullnameOverride: adapter
  valueFiles:
    - values.yaml

tier2_gateway:
  projectID: "860"
  targetRevision: 2.5.0
  chart_name: tier2-gateway
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: "400m"
      memory: "512Mi" 
  valueFiles:
    - values.yaml
    - values-routes-authority.yaml


identity_provider:
  projectID: "913"
  targetRevision: 2.5.2
  chart_name: identity-provider
  fullnameOverride: identity-provider
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  valueFiles:
    - values.yaml

auth_provider:
  projectID: "939"
  targetRevision: 2.5.2
  chart_name: authentication-provider
  resources:
    requests:
      cpu: "400m"
      memory: "400Mi"
    limits:
      cpu: "500m"
      memory: "1Gi" 
  valueFiles:
    - values.yaml

redis:
  repo_URL: 'https://charts.bitnami.com/bitnami'
  targetRevision: 19.6.0
  chart_name: redis
  nameOverride: redis
  resourcesPreset: "none"
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml

redis_commander:
  enabled: false
  repo_URL: 'https://github.com/joeferner/redis-commander.git'
  targetRevision: master
  nameOverride: redis-commander
  path: 'k8s/helm-chart/redis-commander'
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  valueFiles:
    - values.yaml

tier2_proxy:
  projectID: "1112"
  targetRevision: 1.0.1
  chart_name: tier2-proxy
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"

simpl_schema_manager:
  enabled: true
  projectID: "1124"
  targetRevision: 0.0.7
  chart_name: simpl-schema-manager-charts
  fullnameOverride: simpl-schema-manager
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"  
  valueFiles:
    - values.yaml      

monitoring:
  enabled: true
  projectID: "828"
  targetRevision: 0.2.0
  chart_name: eck-monitoring
  fullnameOverride: elastic
  resources:
    filebeat:
      requests:
        memory: "100Mi"
        cpu: "100m"
  valueFiles:
    - values.yaml
