auth:
  adminUser: "admin"
  adminPassword: "admin"

postgresql:
  enabled: false

externalDatabase:
  annotations: {}
  database: keycloak
  existingSecret: ""
  existingSecretDatabaseKey: ""
  existingSecretHostKey: ""
  existingSecretPasswordKey: ""
  existingSecretPortKey: ""
  existingSecretUserKey: ""
  password: keycloak
  port: 5432
  user: keycloak

extraVolumes:
  - name: spi-volume
    emptyDir: {}
  - name: realm-volume
    emptyDir: {}

extraVolumeMounts:
  - name: spi-volume
    mountPath: /opt/bitnami/keycloak/providers/keycloak-authenticator.jar
    subPath: keycloak-authenticator.jar
  - name: realm-volume
    mountPath: /opt/bitnami/keycloak/data/import/realm.json
    subPath: realm.json

image:
  repository: bitnamilegacy/keycloak
security:
  allowInsecureImages: true
  