profile: authority

appConfig:
  springdoc:
    swagger-ui:
      # add other entries if you want to expose additional openapi
      urls: 
        - url: /sapApi/openapi/securityattributesprovider-v1.yaml
          name: Security Attributes Provider Service V1
        - url: /onboardingApi/openapi/onboarding-v1.yaml
          name: Onboarding Service V1
        - url: /userApi/openapi/usersroles-v1.yaml
          name: Users & Roles Service V1
        - url: /identityApi/openapi/identityprovider-v1.yaml
          name: Identity Provider Service V1
        - url: /authApi/openapi/authenticationprovider-v1.yaml
          name: Authentication Provider Service V1
        - url: /openapi/tier1gateway-v1.yaml
          name: Application Info V1

  external-routes:
    spring-route-definitions:
      - id: fc-service
        uri: "http://xsfc-service:8081"
        predicates:
        - Path=/fc/**
        filters:
        - StripPrefix=1
    abac:
      - method: GET
        path: "/fc/**"
        disable-ephemeral-proof-check: true
      - method: POST
        path: "/fc/**"
        disable-ephemeral-proof-check: true
      - method: PUT
        path: "/fc/**"
        disable-ephemeral-proof-check: true
      - method: DELETE
        path: "/fc/**"
        disable-ephemeral-proof-check: true
  
  keycloak:
    app:
      realm: authority
