replica:
  replicaCount: 0
master:
  serviceAccount: 
    create: true
    name: redis-master-service-account
  automountServiceAccountToken: true
  livenessProbe: 
    enabled: false
  readinessProbe:
    enabled: false
architecture: standalone

secretAnnotations:
  vault.security.banzaicloud.io/vault-path: "kubernetes"
  vault.security.banzaicloud.io/vault-skip-verify: "true"

auth:
  existingSecret: redis-secrets
  existingSecretPasswordKey: redis

image:
  repository: redis
  tag: 7.2
security:
  allowInsecureImages: true
  